spring.application.name=folder
app.upload.dir=D:/E-LEARNING/JAVA/QUAN_LY_FILE_CHUAN/media
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# Cho phép render template nhanh để debug
spring.thymeleaf.cache=false